<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE mptopo [
  <!ELEMENT mptopo (caption,groups*)>
  <!ATTLIST mptopo createdBy CDATA #REQUIRED>
  <!ATTLIST mptopo maintainedBy CDATA #REQUIRED>
  <!ATTLIST mptopo copyright CDATA #REQUIRED>
  <!ATTLIST mptopo url CDATA #REQUIRED>
  <!ATTLIST mptopo lastNewMptopoProteinDate CDATA #REQUIRED>
  <!ATTLIST mptopo lastDatabaseEditDate CDATA #REQUIRED>
  <!ATTLIST mptopo timeStamp CDATA #REQUIRED>
  <!ELEMENT caption (#PCDATA)>
  <!ELEMENT groups (group*)>
  <!ELEMENT group (name,mptopoProteins?,subgroups)>
  <!ELEMENT subgroups (subgroup*)>
  <!ELEMENT subgroup (name,mptopoProteins)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT mptopoProteins (mptopoProtein*)>
  <!ELEMENT mptopoProtein (proteinName,species,taxonomicDomain,remarks,pirNumber,
                           uniprotEntry,uniprotNumber,uniprotGene,uniprotName,
                           pdbTitle,pdbCodes,
                           nTerminal,sequence,complexTopology,tmSegments,
                           bibliography,secondaryBibliographies)>
  <!ELEMENT proteinName (#PCDATA)>
  <!ELEMENT species (#PCDATA)>
  <!ELEMENT taxonomicDomain (#PCDATA)>
  <!ELEMENT remarks (#PCDATA)>
  <!ELEMENT pirNumber (#PCDATA)>
  <!ELEMENT uniprotEntry (#PCDATA)>
  <!ELEMENT uniprotNumber (#PCDATA)>
  <!ELEMENT uniprotGene (#PCDATA)>
  <!ELEMENT uniprotName (#PCDATA)>
  <!ELEMENT pdbTitle (#PCDATA)>
  <!ELEMENT pdbCodes (pdbCode*)>
  <!ELEMENT pdbCode (#PCDATA)>
  <!ELEMENT nTerminal (#PCDATA)>
  <!ELEMENT sequence (#PCDATA)>
  <!ELEMENT complexTopology (#PCDATA)>
  <!ELEMENT tmSegments (tmSegment*)>
  <!ELEMENT tmSegment (segLabel,beginIndex,endIndex)>
  <!ELEMENT segLabel (#PCDATA)>
  <!ELEMENT beginIndex (#PCDATA)>
  <!ELEMENT endIndex (#PCDATA)>
  <!ELEMENT bibliography (pubMedId,authors,year,title,journal,volume,issue,pages,doi,notes)>
  <!ELEMENT pubMedId (#PCDATA)>
  <!ELEMENT authors (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT journal (#PCDATA)>
  <!ELEMENT volume (#PCDATA)>
  <!ELEMENT issue (#PCDATA)>
  <!ELEMENT pages (#PCDATA)>
  <!ELEMENT doi (#PCDATA)>
  <!ELEMENT notes (#PCDATA)>
  <!ELEMENT secondaryBibliographies (bibliography*)>
]>
<mptopo createdBy='Stephen White' maintainedBy='Craig Snider' copyright='Copyright Â© 1998-2016 Stephen H. White. All rights reserved.' url='http://blanco.biomol.uci.edu/mptopo/mptopoAlphaHlxTblXml' lastNewMptopoProteinDate='2007-02-07 00:00:00.0' lastDatabaseEditDate='2014-08-06 15:23:10.0' timeStamp='Mon Jan 11 20:49:36 PST 2016'>
  <caption>mptopo database - alpha-helical membrane proteins</caption>
  <groups>
    <group>
      <name>TRANSMEMBRANE PROTEINS: ALPHA-HELICAL</name>
      <subgroups>
        <subgroup>
          <name>Adventitious Membrane Proteins: Alpha-helical Pore-forming Toxins.</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>De novo Designed Membrane Proteins</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Outer Membrane Proteins</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Bacterial Cell Divison Proteins</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Bacterial and Algal Rhodopsins</name>
          <mptopoProteins>
            <mptopoProtein>
              <proteinName>bacteriorhodopsin</proteinName>
              <species>Halobacterium salinarium</species>
              <taxonomicDomain>Archaea</taxonomicDomain>
              <remarks>Sequence below is processed sequence from Swiss-Prot (13 AA signal sequence removed). TMhelices=7.</remarks>
              <pirNumber>RAHSB</pirNumber>
              <uniprotEntry>BACR_HALSA</uniprotEntry>
              <uniprotNumber>P02945</uniprotNumber>
              <uniprotGene>bop</uniprotGene>
              <uniprotName>Bacteriorhodopsin [Precursor]</uniprotName>
              <pdbTitle>bacteriorhodopsin</pdbTitle>
              <pdbCodes>
                <pdbCode>1BRX</pdbCode>
                <pdbCode>2BRD</pdbCode>
                <pdbCode>1AP9</pdbCode>
                <pdbCode>1AT9</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>QAQITGRPEWIWLALGTALMGLGTLYFLVKGMGVSDPDAKKFYAITTLVPAIAFTMYLSMLLGYGLTMVPFGGEQNPIYWARYADWLFTTPLLLLDLALLVDADQGTILALVGADGIMIGTGLVGALTKVYSYRFVWWAISTAAMLYILYVLFFGFTSKAESMRPEVASTFKVLRNVTVVLWSAYPVVWLIGSEGAGIVPLNIETLLFMVLDVSAKVGFGLILLRSRAIFGEAEAPEPSAGDGAAATSD</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>9</beginIndex>
                  <endIndex>31</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>36</beginIndex>
                  <endIndex>63</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>C</segLabel>
                  <beginIndex>81</beginIndex>
                  <endIndex>101</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>D</segLabel>
                  <beginIndex>104</beginIndex>
                  <endIndex>127</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>E</segLabel>
                  <beginIndex>133</beginIndex>
                  <endIndex>155</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>F</segLabel>
                  <beginIndex>164</beginIndex>
                  <endIndex>192</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>G</segLabel>
                  <beginIndex>200</beginIndex>
                  <endIndex>225</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>10452895</pubMedId>
                <authors>Luecke H, Schobert B, Richter HT, Cartailler P, &amp;amp; Lanyi JK</authors>
                <year>1999</year>
                <title>Structure of bacteriorhodopsin at 1.55 angstrom resolution.</title>
                <journal>J. Mol. Biol</journal>
                <volume>291</volume>
                <issue />
                <pages>899-911</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
            <mptopoProtein>
              <proteinName>halorhodopsin</proteinName>
              <species>Halobacterium salinarum</species>
              <taxonomicDomain>Archaea</taxonomicDomain>
              <remarks>Sequence below is unprocessed sequence from Swiss-Prot. AA numbering in PDB file and in the 'tmseg' assignments correspond to unprocessed sequence. Signal sequence corresponds to first 21 AA. TMhelices=7.</remarks>
              <pirNumber>A26161</pirNumber>
              <uniprotEntry>BACH_HALSA</uniprotEntry>
              <uniprotNumber>P16102</uniprotNumber>
              <uniprotGene>HOP,VNG0180G</uniprotGene>
              <uniprotName>Halorhodopsin [Precursor]</uniprotName>
              <pdbTitle>Halorhodopsin - Chain A</pdbTitle>
              <pdbCodes>
                <pdbCode>1E12</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>MSITSVPGVVDAGVLGAQSAAAVRENALLSSSLWVNVALAGIAILVFVYMGRTIRPGRPRLIWGATLMIPLVSISSYLGLLSGLTVGMIEMPAGHALAGEMVRSQWGRYLTWALSTPMILLALGLLADVDLGSLFTVIAADIGMCVTGLAAAMTTSALLFRWAFYAISCAFFVVVLSALVTDWAASASSAGTAEIFDTLRVLTVVLWLGYPIVWAVGVEGLALVQSVGVTSWAYSVLDVFAKYVFAFILLRWVANNERTVAVAGQTLGTMSSDD</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>26</beginIndex>
                  <endIndex>51</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>58</beginIndex>
                  <endIndex>81</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>C</segLabel>
                  <beginIndex>106</beginIndex>
                  <endIndex>127</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>D</segLabel>
                  <beginIndex>131</beginIndex>
                  <endIndex>154</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>E</segLabel>
                  <beginIndex>158</beginIndex>
                  <endIndex>180</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>F</segLabel>
                  <beginIndex>193</beginIndex>
                  <endIndex>216</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>G</segLabel>
                  <beginIndex>227</beginIndex>
                  <endIndex>255</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>10827943</pubMedId>
                <authors>Kolbe M, Besir H, Essen L-O, &amp;amp; Oesterhelt D</authors>
                <year>2000</year>
                <title>Structure of the light-driven chloride pump halorhodopsin at 1.8 &amp;Aring;.</title>
                <journal>Science</journal>
                <volume>288</volume>
                <issue />
                <pages>1390-1396</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
            <mptopoProtein>
              <proteinName>sensory rhodopsin</proteinName>
              <species>Anabaena</species>
              <taxonomicDomain>Bacteria</taxonomicDomain>
              <remarks>Sequence from PDB</remarks>
              <pirNumber>AF2201</pirNumber>
              <uniprotEntry>Q8YSC4_ANASP</uniprotEntry>
              <uniprotNumber>Q8YSC4</uniprotNumber>
              <uniprotGene>alr3165</uniprotGene>
              <uniprotName>bacteriorhodopsin</uniprotName>
              <pdbTitle>Anabaena sensory rhodopsin</pdbTitle>
              <pdbCodes>
                <pdbCode>1XIO</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>MNLESLLHWIYVAGMTIGALHFWSLSRNPRGVPQYEYLVAMFIPIWSGLAYMAMAIDQGKVEAAGQIAHYARYIDWMVTTPLLLLSLSWTAMQFIKKDWTLIGFLMSTQIVVITSGLIADLSERDWVRYLWYICGVCAFLIILWGIWNPLRAKTRTQSSELANLYDKLVTYFTVLWIGYPIVWIIGPSGFGWINQTIDTFLFCLLPFFSKVGFSFLDLHGLRNLNDSRQTTGDRFAENTLQFVENITLFANSRRQQSRRRV</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>3</beginIndex>
                  <endIndex>26</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>34</beginIndex>
                  <endIndex>56</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>C</segLabel>
                  <beginIndex>72</beginIndex>
                  <endIndex>91</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>D</segLabel>
                  <beginIndex>99</beginIndex>
                  <endIndex>121</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>E</segLabel>
                  <beginIndex>125</beginIndex>
                  <endIndex>147</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>F</segLabel>
                  <beginIndex>159</beginIndex>
                  <endIndex>185</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>G</segLabel>
                  <beginIndex>195</beginIndex>
                  <endIndex>209</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>15459346</pubMedId>
                <authors>Vogeley L, Sineshchekov OA, Trivedi VD, Sasaki J, Spudich JL, &amp;amp; Luecke H</authors>
                <year>2004</year>
                <title>Anabaena sensory rhodopsin: a photochromic color sensor at 2.0 &amp;Aring;.</title>
                <journal>Science</journal>
                <volume>306</volume>
                <issue />
                <pages>1390-1393</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
            <mptopoProtein>
              <proteinName>sensory rhodopsin II</proteinName>
              <species>Natronomonas pharaonis</species>
              <taxonomicDomain>Archaea</taxonomicDomain>
              <remarks>Sequence is from Swiss-Prot. TMhelices=7.</remarks>
              <pirNumber>S55300</pirNumber>
              <uniprotEntry>BACT_NATPH</uniprotEntry>
              <uniprotNumber>P42196</uniprotNumber>
              <uniprotGene>SOP2,SOPII</uniprotGene>
              <uniprotName>Sensory rhodopsin II</uniprotName>
              <pdbTitle>Sensory Rhodopsin II</pdbTitle>
              <pdbCodes>
                <pdbCode>1H68</pdbCode>
                <pdbCode>1JGJ</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>MVGLTTLFWLGAIGMLVGTLAFAWAGRDAGSGERRYYVTLVGISGIAAVAYVVMALGVGWVPVAERTVFAPRYIDWILTTPLIVYFLGLLAGLDSREFGIVITLNTVVMLAGFAGAMVPGIERYALFGMGAVAFLGLVYYLVGPMTESASQRSSGIKSLYVRLRNLTVILWAIYPFIWLLGPPGVALLTPTVDVALIVYLDLVTKVGFGFIALDAAATLRAEHGESLAGVDTDAPAVAD</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>3</beginIndex>
                  <endIndex>26</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>33</beginIndex>
                  <endIndex>56</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>C</segLabel>
                  <beginIndex>70</beginIndex>
                  <endIndex>92</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>D</segLabel>
                  <beginIndex>94</beginIndex>
                  <endIndex>118</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>E</segLabel>
                  <beginIndex>122</beginIndex>
                  <endIndex>150</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>F</segLabel>
                  <beginIndex>153</beginIndex>
                  <endIndex>181</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>G</segLabel>
                  <beginIndex>189</beginIndex>
                  <endIndex>219</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>11504917</pubMedId>
                <authors>Royant A, Nollert P, Edman K, Neutze R, Landau EM, &amp;amp; Pebay-Peyroula E.</authors>
                <year>2001</year>
                <title>X-ray structure of sensory rhodopsin II at 2.1 &amp;Aring; resolution.</title>
                <journal>Proc Natl Acad Sci USA</journal>
                <volume>98</volume>
                <issue />
                <pages>10131-10136</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
            <mptopoProtein>
              <proteinName>sensory rhodopsin transducer</proteinName>
              <species>Natronomonas pharaonis</species>
              <taxonomicDomain>Archaea</taxonomicDomain>
              <remarks>Sequence from Swiss-Prot. PDB sequence is truncated at N- &amp; C-terminii. TMhelices=2.</remarks>
              <pirNumber>S55299</pirNumber>
              <uniprotEntry>HTR2_NATPH</uniprotEntry>
              <uniprotNumber>P42259</uniprotNumber>
              <uniprotGene>HTR2,HTRII</uniprotGene>
              <uniprotName>Sensory rhodopsin II transducer</uniprotName>
              <pdbTitle>rhodopsin II-transducer complex</pdbTitle>
              <pdbCodes>
                <pdbCode>1H2S</pdbCode>
              </pdbCodes>
              <nTerminal>in</nTerminal>
              <sequence>MSLNVSRLLLPSRVRHSYTGKMGAVFIFVGALTVLFGAIAYGEVTAAAATGDAAAVQEAAVSAILGLIILLGINLGLVAATLGGDTAASLSTLAAKASRMGDGDLDVELETRREDEIGDLYAAFDEMRQSVRTSLEDAKNAREDAEQAQKRAEEINTELQAEAERFGEVMDRCADGDFTQRLDAETDNEAMQSIEGSFNEMMDGIEALVGRIERFADAVSEDAEAVRANAESVMEASEDVNRAVQNISDAAGDQTETVQQIALEMDDVSATTEEVAASADDIAKTARQAAETGEAGRETAETAITEMNEVESRTEQAVASMEELNEDVREIGEVSEMIADIAEQTNILALNASIEAARADGNSEGFAVVADEVKALAEETKAATEEIDDLIGTVQDRTQTTVDDIRETSDQVSEGVETVEDTVDALERIVDSVERTNDGIQEINQSTDAQADAAQKATTMVEDMAATSEQTASDAETAAETTETQAESVKEVFDLIDGLSEQADSLSETLSRTDTEEASAADLDDQPTLAAGDD</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>24</beginIndex>
                  <endIndex>49</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>54</beginIndex>
                  <endIndex>80</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>12368857</pubMedId>
                <authors>Gordeliy VI, Labahn J, Moukhametzianov R, Efremov R, Granzin J, Schlesinger R, BÃ¼ldt G, Savopol T, Scheidig AJ, Klare JP, &amp;amp; Engelhard M.</authors>
                <year>2002</year>
                <title>Molecular basis of transmembrane signalling by sensory rhodopsin II-transducer complex.</title>
                <journal>Nature</journal>
                <volume>419</volume>
                <issue />
                <pages>484-487</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
          </mptopoProteins>
        </subgroup>
        <subgroup>
          <name>G Protein-Coupled Receptors (GPCRs)</name>
          <mptopoProteins>
            <mptopoProtein>
              <proteinName>rhodopsin</proteinName>
              <species>Bos taurus (Bovine)</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <remarks>Sequence from Swiss-Prot. TMhelices=7.</remarks>
              <pirNumber>OOBO</pirNumber>
              <uniprotEntry>OPSD_BOVIN</uniprotEntry>
              <uniprotNumber>P02699</uniprotNumber>
              <uniprotGene>RHO</uniprotGene>
              <uniprotName>Rhodopsin</uniprotName>
              <pdbTitle>crystal structure of bovine rhodopsin - Chain A, B</pdbTitle>
              <pdbCodes>
                <pdbCode>1F88</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>MNGTEGPNFYVPFSNKTGVVRSPFEAPQYYLAEPWQFSMLAAYMFLLIMLGFPINFLTLYVTVQHKKLRTPLNYILLNLAVADLFMVFGGFTTTLYTSLHGYFVFGPTGCNLEGFFATLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLVGWSRYIPEGMQCSCGIDYYTPHEETNNESFVIYMFVVHFIIPLIVIFFCYGQLVFTVKEAAAQQQESATTQKAEKEVTRMVIIMVIAFLICWLPYAGVAFYIFTHQGSDFGPIFMTIPAFFAKTSAVYNPVIYIMMNKQFRNCMVTTLCCGKNPLGDDEASTTVSKTETSQVAPA</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>35</beginIndex>
                  <endIndex>64</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>71</beginIndex>
                  <endIndex>100</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>C</segLabel>
                  <beginIndex>107</beginIndex>
                  <endIndex>139</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>D</segLabel>
                  <beginIndex>151</beginIndex>
                  <endIndex>173</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>E</segLabel>
                  <beginIndex>200</beginIndex>
                  <endIndex>225</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>F</segLabel>
                  <beginIndex>247</beginIndex>
                  <endIndex>277</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>G</segLabel>
                  <beginIndex>286</beginIndex>
                  <endIndex>306</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>10926528</pubMedId>
                <authors>Palczewski K, Kumasaka T, Hori T, Behnke CA, Motoshima H, Fox BA, Le Trong I, Teller DC, Okada T, Stenkamp RE, Yamamoto M, &amp;amp; Miyano M</authors>
                <year>2000</year>
                <title>Crystal structure of rhodopsin: A G protein-coupled receptor.</title>
                <journal>Science</journal>
                <volume>289</volume>
                <issue />
                <pages>739-745</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
          </mptopoProteins>
        </subgroup>
        <subgroup>
          <name>Adiponectin Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Autonomously Folding &amp;quot;Membrane Proteins&amp;quot; (Sec-independent)</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Virus Coat Proteins</name>
          <mptopoProteins>
            <mptopoProtein>
              <proteinName>M13 coat protein</proteinName>
              <species>Enterobacteria phage m13</species>
              <taxonomicDomain>Viruses</taxonomicDomain>
              <remarks>S-P differs from PDB sequence at two residue positions. Sequence from PDB. TMhelices=1.</remarks>
              <pirNumber></pirNumber>
              <uniprotEntry>COAB_BPZJ2</uniprotEntry>
              <uniprotNumber>P03618</uniprotNumber>
              <uniprotGene>VIII</uniprotGene>
              <uniprotName>Coat protein B</uniprotName>
              <pdbTitle>M13 major coat protein</pdbTitle>
              <pdbCodes>
                <pdbCode>2CPB</pdbCode>
                <pdbCode>2CPS</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>AEGDDPAKAAFNSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKAS</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>24</beginIndex>
                  <endIndex>45</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>9735296</pubMedId>
                <authors>Papavoine CH, Christiaans BE, Folmer RH, Konings RN, &amp;amp; Hilbers CW</authors>
                <year>1998</year>
                <title>Solution structure of the M13 major coat protein in detergent micelles: a basis for a model of phage assembly involving specific residues.</title>
                <journal>J Mol Biol</journal>
                <volume>282</volume>
                <issue />
                <pages>401-419</pages>
                <doi>10.1006/jmbi.1998.1860</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
          </mptopoProteins>
        </subgroup>
        <subgroup>
          <name>Glycoproteins</name>
          <mptopoProteins>
            <mptopoProtein>
              <proteinName>glycophorin A</proteinName>
              <species>Homo sapiens</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <remarks>Sequence is processed sequence from Swiss-Prot (19 AA signal sequence removed). TMhelices=1.</remarks>
              <pirNumber>GFHUE</pirNumber>
              <uniprotEntry>GLPA_HUMAN</uniprotEntry>
              <uniprotNumber>P02724</uniprotNumber>
              <uniprotGene>GYPA,GPA</uniprotGene>
              <uniprotName>Glycophorin A [Precursor]</uniprotName>
              <pdbTitle>Glycophorin A, Chain A</pdbTitle>
              <pdbCodes>
                <pdbCode>1AFO</pdbCode>
              </pdbCodes>
              <nTerminal>out</nTerminal>
              <sequence>SSTTGVAMHTSTSSSVTKSYISSQTNDTHKRDTYAATPRAHEVSEISVRTVYPPEEETGERVQLAHHFSEPEITLIIFGVMAGVIGTILLISYGIRRLIKKSPSDVKPLPSPDTDVPLSSVEIENPETSDQ</sequence>
              <complexTopology>false</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>73</beginIndex>
                  <endIndex>95</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>9082985</pubMedId>
                <authors>MacKenzie KR, Prestegard JH, &amp;amp; Engelman DM</authors>
                <year>1997</year>
                <title>A transmembrane helix dimer: structure and implications.</title>
                <journal>Science</journal>
                <volume>276</volume>
                <issue />
                <pages>131-133</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
            </mptopoProtein>
          </mptopoProteins>
        </subgroup>
        <subgroup>
          <name>Receptor Tyrosine Kinase (RTK) Family</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Epidermal Growth Factor Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Erythropoietin-Producing Hepatocellular Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Fibroblast Growth Factor Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Vascular Endothelial Growth Factor Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Integrin Adhesion Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Histidine Kinase Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Immune Receptors</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>SNARE Protein Family</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Claudins</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>TMEM16 Family Proteins</name>
          <mptopoProteins />
        </subgroup>
        <subgroup>
          <name>Channels: Potassium, Sodium, &amp; Proton Ion-Selective</name>
          <mptopoProteins>
            <mptopoProtein>
              <proteinName>KcsA potassium channel</proteinName>
              <species>Streptomyces lividans</species>
              <taxonomicDomain>Bacteria</taxonomicDomain>
              <remarks>*The 'tmsegs' marked below include the so-called pore helix (P) associated with the pore region. 'tmseg' B corresponds to P. TMhelices=2.</remarks>
              <pirNumber>S60172</pirNumber>
              <uniprotEntry>KCSA_STRCO</uniprotEntry>
              <uniprotNumber>Q54397</uniprotNumber>
              <uniprotGene>KCSA,SKC1,SCO7660,SC10F4.33</uniprotGene>
              <uniprotName>Voltage-gated potassium channel</uniprotName>
              <pdbTitle>Potassium Channel (KcsA) from Streptomyces lividans</pdbTitle>
              <pdbCodes>
                <pdbCode>1BL8</pdbCode>
              </pdbCodes>
              <nTerminal>in</nTerminal>
              <sequence>MPPMLSGLLARLVKLLLGRHGSALHWRAAGAATVLLVIVLLAGSYLAVLAERGAPGAQLITYPRALWWSVETATTVGYGDLYPVTLWGRCVAVVVMVAGITSFGLVTAALATWFVGREQ</sequence>
              <complexTopology>true</complexTopology>
              <tmSegments>
                <tmSegment>
                  <segLabel>A</segLabel>
                  <beginIndex>28</beginIndex>
                  <endIndex>52</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>B</segLabel>
                  <beginIndex>62</beginIndex>
                  <endIndex>72</endIndex>
                </tmSegment>
                <tmSegment>
                  <segLabel>C</segLabel>
                  <beginIndex>87</beginIndex>
                  <endIndex>113</endIndex>
                </tmSegment>
              </tmSegments>
              <bibliography>
                <pubMedId>9525859</pubMedId>
                <authors>Doyle DA, Cabral JM, Pfuetzner RA, Kuo AL, Gulbis JM, Cohen SL, Chait BT, &amp;amp; MacKinnon R</authors>
                <year>1998</year>
                <title>The structure of the potassium channel: Molecular basis of K&lt;sup&gt;+&lt;/sup&gt;conduction and selectivity.</title>
                <journal>Science </journal>
                <volume>280</volume>
                <issue />
                <pages>69-77</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>